const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Plugins.gamepad,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{DirectionCode: 0},
	{DiscInHand: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{TiledBackground: 0},
	{Gamepad: 0},
	{Solid: 0},
	{tree: 0},
	{Anchor: 0},
	{debugtext: 0},
	{Pin: 0},
	{PlayerAnimation: 0},
	{powerbarborder: 0},
	{PowerAmount: 0},
	{powerbar: 0},
	{IsThrown: 0},
	{Bullet: 0},
	{disc001: 0},
	{lightgrass: 0},
	{Sprite: 0},
	{holeMap: 0},
	{basket: 0},
	{Text: 0},
	{HoleScore: 0},
	{Score: 0},
	{FinalHoleScore: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Gamepad: class extends self.IInstance {},
	tree: class extends self.ISpriteInstance {},
	debugtext: class extends self.ITextInstance {},
	PlayerAnimation: class extends self.ISpriteInstance {},
	powerbarborder: class extends self.ISpriteInstance {},
	powerbar: class extends self.ISpriteInstance {},
	disc001: class extends self.ISpriteInstance {},
	lightgrass: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	holeMap: class extends self.ISpriteInstance {},
	basket: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Score: class extends self.ITextInstance {},
	FinalHoleScore: class extends self.ITextInstance {}
}